config/routes.rb
Rails.application.routes.draw do
  resources :faqs
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only:[:create]
  resources :registrations, only:[:create]
  

  # events
  get '/events/front' => 'events#front', as: :manage_posts
  resources :events do
    member do
      delete :delete_image
    end

  	put 'publish' => 'events#publish',
  	on: :member, as: :publish
  
  	put 'unpublish' => 'events#unpublish', 
  	on: :member, as: :unpublish
  end

  #resources :messages
  resources :messages, :path => "contact_us"

  #static_pages
  get "/about" , to: 'static_pages#about'
  get "/join_us", to: 'messages#new'
  get "/home", to: 'static_pages#home'
  get "/maintenance", to: 'static_pages#maintenance'

  #sessions
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#logout'
  get "sessions/status"

  #registrations
  get "/signup", to: 'registrations#new'
  post "/signup", to: 'registrations#create'

  #search_page
  get '/search', to: 'search_page#search'

  #sitemap
  get '/sitemap', to: 'sitemap#index', defaults: {format: "xml"}
end

app/models/message.rb
class Message < ApplicationRecord
    # attr_accessor :name, :email, :message_body
    validates_presence_of :name, :email, :message_body

    default_scope { order(created_at: :desc) }
    # scope :latest, -> { order(created_at: :desc)}
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
    before_action :set_message, only: [:show, :destroy]

    def new
        @message = Message.new
    end 

    def show
    end 

    def create
        @message = Message.new(message_params)

        respond_to do |format|
            if @message.save
              MessageMailer.contact_me(@message).deliver_now
              format.html { redirect_to new_message_url, notice: "We've received the message and will get back to you soon!" }
              format.json { render :new, status: :created, location: @message }
            else
              format.html {redirect_to new_message_url, notice: "Please fill in all fields."}
              # format.html { render :new }
              format.json { render json: @message.errors, status: :unprocessable_entity }
            end
          end

        #if @message.save
        #    redirect_to new_message_url, notice: "We've received the message and will get back to you soon!"
        #else r
        #    render 'new'
        #end 
    end 

    def index
        @messages = Message.all
        # Alternative: @messages = Message.paginate(page: params[:page], per_page: 5)
    end 

    def destroy
        @message.destroy
        respond_to do |format|
          format.html { redirect_to messages_url, notice: 'Message was successfully deleted.' }
          format.json { head :no_content }
        end
    end

    private
    def set_message
        @message = Message.find(params[:id])
    end 

    def message_params
        params.require(:message).permit(:name, :email, :message_body)
    end 
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/messages/index.html.erb
<% provide(:page_title, "All Messages") %>

<p id="notice" class="text-success"><%= notice %></p>

<div id="message" class="container-fluid d-flex justify-content-center">
  <div class="col-8">
  
  <h1 class="text-dark">
    All Messages
    <p class="btn text-small"> <%= @messages.count %> New </p>       
  </h1>

    <% @messages.each do |message| %>
      <div class="card">
        <div class="card-header text-muted">
            <p><%= message.created_at.strftime('%-b %-d, %Y') %> </p>
        </div>
        <div class="card-body">
          <div class="card-text"> <p> <%= message.message_body %> </p></div>
          <div class="card-text">
            <div class="row justify-content-end">
               <p class="text-muted"> ~ <%= message.name %> |  <%= message.email %> </p>
            </div>
          </div>
        </div>
        <div class="card-footer text-muted">
          <div class="card-text"> 
            <p><%= link_to 'Resolved', message_path(message), method: :delete, data: { confirm: 'Are you certain you have resolved this?' } %> </p>            
          </div>   
        </div>
      </div>
    <% end %>
  </div>

</div>

app/views/messages/new.html.erb
<% provide(:page_title, "Contact Us") %>

<div class="container-fluid" id="contact-us">
  <div class="row hero">
    <div class="container">
      <div class="row">
        <div class="col mt-3">
          <h1>Contact us</h1>
        </div>
      </div>

      <!-- start of email -->
      <div class="row justify-content-center">
        <a href="mailto:nusguitarensemble@gmail.com">nusguitarensemble@gmail.com</a>
      </div>
      <!-- end of email -->

      <hr>


      <!-- start of icons -->
      <div class="row">
        <div class="col-4">
        </div>
        <div class="col-4 d-flex justify-content-center">
          <a href="https://www.facebook.com/NUSGuitarEnsemble/" id="icon"><i class="fab fa-facebook-square"></i></a>
          <a href="https://www.youtube.com/user/NusGuitarEnsemble" id="icon"><i class="fab fa-youtube"></i></a>
          <a href="https://www.instagram.com/nusguitarensemble/" id="icon"><i class="fab fa-instagram"></i></a>
        </div>
        <div class="col-4">
        </div>
      </div>
      <!-- end of icons -->

      <div class="row py-3">
        <div class="col-md-6 contact-detail-left">
          <!-- Form for contact message -->
          <%= form_for @message, url: {action: "create"} do |f| %>
            <!-- Errors if any -->
            <% if @message.errors.any? %>
              <div id="error_explanation">
                <ul>
                  <% @message.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                  <% end %>
                </ul>
              </div>
            <% end %>

            <!-- Form fields -->
            <div class="field">
              <%= f.text_field :name, placeholder: 'Name *', size: "40", class: "col-12" %>
            </div>

            <div class="field">
              <%= f.email_field :email, placeholder: 'Email *', class: "col-12" %>
            </div>

            <div class="field">
              <%= f.text_area :message_body, placeholder: 'Leave us your question and we will get back to you soon!', size: "40x8", class: "col-12" %>
            </div>

            <div class="actions">
              <%= f.submit 'Send', class: "col-12 btn" %>
            </div>
          <% end %>
          <!-- End of Form -->
        </div>

        <!-- start of Google Maps -->
        <div class="col-md-6 contact-detail-right">
          <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3988.7925696931566!2d103.77159691405718!3d1.2992456620995538!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x31da1af78cce2317%3A0x130a63b0e55d5d43!2sRunme+Shaw+CFA+Studios!5e0!3m2!1sen!2ssg!4v1564846462846!5m2!1sen!2ssg" width="350" height="295" frameborder="0" style="border:0" allowfullscreen></iframe>
        </div>
        <!-- end of Google Maps -->
      </div>


    </div>
  </div>
</div>