config/routes.rb
Rails.application.routes.draw do
  resources :faqs
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only:[:create]
  resources :registrations, only:[:create]
  

  # events
  get '/events/front' => 'events#front', as: :manage_posts
  resources :events do
    member do
      delete :delete_image
    end

  	put 'publish' => 'events#publish',
  	on: :member, as: :publish
  
  	put 'unpublish' => 'events#unpublish', 
  	on: :member, as: :unpublish
  end

  #resources :messages
  resources :messages, :path => "contact_us"

  #static_pages
  get "/about" , to: 'static_pages#about'
  get "/join_us", to: 'messages#new'
  get "/home", to: 'static_pages#home'
  get "/maintenance", to: 'static_pages#maintenance'

  #sessions
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#logout'
  get "sessions/status"

  #registrations
  get "/signup", to: 'registrations#new'
  post "/signup", to: 'registrations#create'

  #search_page
  get '/search', to: 'search_page#search'

  #sitemap
  get '/sitemap', to: 'sitemap#index', defaults: {format: "xml"}
end

app/models/faq.rb
class Faq < ApplicationRecord
end

app/controllers/faqs_controller.rb
class FaqsController < ApplicationController
  before_action :set_faq, only: [:show, :edit, :update, :destroy]

  # GET /faqs
  # GET /faqs.json
  def index
    @faqs = Faq.all
  end

  # GET /faqs/1
  # GET /faqs/1.json
  def show
  end

  # GET /faqs/new
  def new
    @faq = Faq.new
  end

  # GET /faqs/1/edit
  def edit
  end

  # POST /faqs
  # POST /faqs.json
  def create
    @faq = Faq.new(faq_params)

    respond_to do |format|
      if @faq.save
        format.html { redirect_to @faq, notice: 'Faq was successfully created.' }
        format.json { render :show, status: :created, location: @faq }
      else
        format.html { render :new }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /faqs/1
  # PATCH/PUT /faqs/1.json
  def update
    respond_to do |format|
      if @faq.update(faq_params)
        format.html { redirect_to @faq, notice: 'Faq was successfully updated.' }
        format.json { render :show, status: :ok, location: @faq }
      else
        format.html { render :edit }
        format.json { render json: @faq.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /faqs/1
  # DELETE /faqs/1.json
  def destroy
    @faq.destroy
    respond_to do |format|
      format.html { redirect_to faqs_url, notice: 'Faq was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_faq
      @faq = Faq.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def faq_params
      params.require(:faq).permit(:question, :answer)
    end
end

app/helpers/faqs_helper.rb
module FaqsHelper
end

app/views/faqs/_form.html.erb
<%= form_with(model: faq, local: true) do |form| %>
  <% if faq.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(faq.errors.count, "error") %> prohibited this faq from being saved:</h2>

      <ul>
        <% faq.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :question %>
    <%= form.text_field :question, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :answer %>
    <%= form.text_area :answer, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit "Submit", class: 'btn' %>
  </div>
<% end %>

app/views/faqs/edit.html.erb
<div class="container">
  <div class="row">
    <h1>Edit Faq</h1>
  </div>

  <%= render 'form', faq: @faq %>

  <%= link_to 'Back', faqs_path %>
</div>

app/views/faqs/index.html.erb
<% provide(:page_title, "FAQs") %>
<% if @current_user %>

  <p id="notice"><%= notice %></p>

  <h1>Faqs</h1>

  <%= link_to 'New Faq', new_faq_path %>

  <br>

  <table>
    <thead>
    <tr>
      <th>Question</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
    </thead>

    <tbody>
    <% @faqs.each do |faq| %>
      <tr>
        <td><%= faq.question %></td>
        <td><%= faq.answer %></td>
        <td><%= link_to 'Show', faq %></td>
        <td><%= link_to 'Edit', edit_faq_path(faq) %></td>
        <td><%= link_to 'Destroy', faq, method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
    <% end %>
    </tbody>
  </table>

<% else %>

  <div class="container" id="faq">
    <div class="row justify-content-center pt-3">
      <h1>FAQs</h1>
    </div>

    <div class="row">
      <div class="col d-flex justify-content-center">
        <div class="accordion" id="accordionExample">
          <% @faqs.each do |faq| %>
            <% if faq == @faqs[0] %>
              <div class="card">
                <div class="card-header" id="heading<%= faq.id.to_s %>" style="width: 90vw;">
                  <h2 class="mb-0">
                    <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapse<%= faq.id.to_s %>" aria-expanded="true" aria-controls="collapse<%= faq.id.to_s %>">
                      <h5 class="m-0"><%= faq.question %></h5>
                    </button>
                  </h2>
                </div>

                <div id="collapse<%= faq.id.to_s %>" class="collapse show" aria-labelledby="heading<%= faq.id.to_s %>" data-parent="#accordionExample">
                  <div class="card-body" style="width: 90vw;">
                    <%= faq.answer %>
                  </div>
                </div>
              </div>
            <% else %>
              <div class="card">
                <div class="card-header" id="heading<%= faq.id.to_s %>" style="width: 90vw;">
                  <h2 class="mb-0">
                    <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapse<%= faq.id.to_s %>" aria-expanded="false" aria-controls="collapse<%= faq.id.to_s %>">
                      <h5 class="m-0"><%= faq.question %></h5>
                    </button>
                  </h2>
                </div>
                <div id="collapse<%= faq.id.to_s %>" class="collapse" aria-labelledby="heading<%= faq.id.to_s %>" data-parent="#accordionExample">
                  <div class="card-body" style="width: 90vw;">
                    <%= faq.answer %>
                  </div>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/faqs/new.html.erb
<div class="container">
  <div class="row">
    <h1>New Faq</h1>
  </div>

  <%= render 'form', faq: @faq %>

  <%= link_to 'Back', faqs_path %>
</div>

app/views/faqs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Question:</strong>
  <%= @faq.question %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @faq.answer %>
</p>

<%= link_to 'Edit', edit_faq_path(@faq) %> |
<%= link_to 'Back', faqs_path %>