config/routes.rb
Rails.application.routes.draw do
  resources :faqs
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only:[:create]
  resources :registrations, only:[:create]
  

  # events
  get '/events/front' => 'events#front', as: :manage_posts
  resources :events do
    member do
      delete :delete_image
    end

  	put 'publish' => 'events#publish',
  	on: :member, as: :publish
  
  	put 'unpublish' => 'events#unpublish', 
  	on: :member, as: :unpublish
  end

  #resources :messages
  resources :messages, :path => "contact_us"

  #static_pages
  get "/about" , to: 'static_pages#about'
  get "/join_us", to: 'messages#new'
  get "/home", to: 'static_pages#home'
  get "/maintenance", to: 'static_pages#maintenance'

  #sessions
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#logout'
  get "sessions/status"

  #registrations
  get "/signup", to: 'registrations#new'
  post "/signup", to: 'registrations#create'

  #search_page
  get '/search', to: 'search_page#search'

  #sitemap
  get '/sitemap', to: 'sitemap#index', defaults: {format: "xml"}
end

app/models/event.rb
class Event < ApplicationRecord
  acts_as_taggable
  has_many_attached :images
  has_one_attached :thumbnail

  extend FriendlyId
  friendly_id :title, use: :slugged

  scope :most_recent, -> { order(start_date: :desc) }
  scope :least_recent, -> { order(start_date: :asc) }
  scope :published, -> { where(published: true) }
  validates :title, presence: true
  validates :content, presence: true
  validate :image_type
  validates :thumbnail, presence: true

  def should_generate_new_friendly_id?
    title_changed?
  end

  def published_date
    if (published)
      "Published #{published_at.strftime('%-b %-d, %Y')}"
    else
      "Not published yet"
    end
  end

  def resize_image input
    return self.images[input].variant(resize: "200x200!").processed
  end

  def image_type
    if thumbnail.attached?
      if !thumbnail.content_type.in?(%('image/jpeg image/png image/jpg'))
        errors.add(:thumbnail, "not in JPEG or PNG or JPG form")
      end
    end

    if images.attached?
      images.each do |image|
        if !image.content_type.in?(%('image/jpeg image/png image/jpg'))
          errors.add(:images, "not in JPEG or PNG or JPG form")
        end
      end
    end
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy, :publish, :unpublish]


  # GET /events
  # GET /events.json
  def index
    if params[:event_type] == "Upcoming"
      @events = Event.least_recent.published.where(:event_type => "Upcoming").paginate(page: params[:page], per_page: 6)
      @title = "Upcoming"
    else
      @title = "Gallery"
      @development_events = Event.least_recent.published.where(:event_type => "Musical Development").paginate(page: params[:page], per_page: 6)
      @bonding_events = Event.least_recent.published.where(:event_type => "Bonding").paginate(page: params[:page], per_page: 6)
      @production_events = Event.least_recent.published.where(:event_type => "Performance & Production").paginate(page: params[:page], per_page: 6)
    end
  end

  def front
    if (params[:tag].present?)
      @events = Event.most_recent.tagged_with(params[:tag]).paginate(page: params[:page], per_page: 6)
    else
      @events = Event.most_recent.paginate(page: params[:page], per_page: 6)
    end
    @tags = Event.tag_counts_on(:tags)
  end

  def publish
    @event.update(published: true, published_at: Time.now)

    respond_to do |format|
      format.html { redirect_to manage_posts_path }
      format.js
    end
  end

  def unpublish
    @event.update(published: false, published_at: nil)

    respond_to do |format|
      format.html { redirect_to manage_posts_path }
      format.js
    end
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html {redirect_to @event, notice: 'Event was successfully created.'}
        format.json {render :show, status: :created, location: @event}
      else
        format.html {render :new}
        format.json {render json: @event.errors, status: :unprocessable_entity}
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html {redirect_to @event, notice: 'Event was successfully updated.'}
        format.json {render :show, status: :ok, location: @event}
      else
        format.html {render :edit}
        format.json {render json: @event.errors, status: :unprocessable_entity}
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html {redirect_to manage_posts_path, notice: 'Event was successfully destroyed.'}
      format.json {head :no_content}
    end
  end

  def delete_image
    @image = ActiveStorage::Attachment.find(params[:images_id])
    @image.purge
    redirect_to event_path(params[:event_id])
  end

  def delete_video
    @video = ActiveStorage::Attachment.find(params[:videos_id])
    @video.purge
    redirect_to event_path(params[:event_id])
  end


  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.friendly.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def event_params
    params.require(:event).permit(:title, :event_type, :thumbnail_type, :tag_list, :start_date, :end_date, :content, :thumbnail,  images: [])
  end
end

app/helpers/events_helper.rb
module EventsHelper
	include ActsAsTaggableOn::TagsHelper
end

app/views/events/_event.html.erb
<div class="col-md-6 col-lg-4 mt-5">
  <div style="width: 100%;">
    <div class="card shadow event-card" style="width: 100%;">
      <!--Card image-->
      <div class="bg-dark d-flex justify-content-center">
        <% if event.thumbnail.attached? %>
          <% if event.thumbnail_type.eql?("Portrait") %>
            <%= image_tag event.thumbnail, class: 'portrait' %>
          <% else %>
            <%= image_tag event.thumbnail, class: 'landscape' %>
          <% end %>
        <% end %>
      </div>

      <!--Card content-->
      <div class="card-body">
        <!--Title-->
        <h4 class="card-title"><%= event.title %></h4><!--Text-->
        <p class="card-text">
          <% if !event.start_date.nil? && !event.end_date.nil? %>
            Date: <%= event.start_date.strftime("%d %b %Y") %> - <%= event.end_date.strftime("%d %b %Y") %>
          <% end %>
        </p>
        <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
        <%= link_to event_path(event), class: 'stretched-link' do %>
          <div class="btn">
            <%= fa_icon "search" %>
            find out more
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
        <% event.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :start_date %>
    <%= form.date_field :start_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :end_date %>
    <%= form.date_field :end_date, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :thumbnail %>
    <%= form.file_field :thumbnail, direct_upload: true, class: 'form-control-file' %>
  </div>

  <div class="form-group">
    <%= form.label :images %>
    <%= form.file_field :images, multiple: true, direct_upload: true, class: 'form-control-file' %>
  </div>

  <%= render 'events/resources', event: @event %>

  <p>Please indicate if the event you are creating is an upcoming one or past one</p>
  <div class="custom-control custom-radio custom-control-inline">
    <%= form.label :event_type, class: 'radio inline' do %>
      <%= form.radio_button :event_type, 'Upcoming', checked: true, class: 'form-check-input' %>
      <span class="form-check-label">Upcoming event</span>
    <% end %>
  </div>
  <div class="custom-control custom-radio custom-control-inline">
    <%= form.label :event_type, class: 'radio inline' do %>
      <%= form.radio_button :event_type, 'Performance & Production', class: 'form-check-input' %>
      <span class="form-check-label">Performance & Production</span>
    <% end %>
  </div>
  <div class="custom-control custom-radio custom-control-inline">
    <%= form.label :event_type, class: 'radio inline' do %>
      <%= form.radio_button :event_type, 'Musical Development', class: 'form-check-input' %>
      <span class="form-check-label">Musical Development</span>
    <% end %>
  </div>
  <div class="custom-control custom-radio custom-control-inline">
    <%= form.label :event_type, class: 'radio inline' do %>
      <%= form.radio_button :event_type, 'Bonding', class: 'form-check-input' %>
      <span class="form-check-label">Bonding</span>
    <% end %>
  </div>

  <p>Please indicate if the portrait photo you provide is portrait or landscape</p>
  <div class="custom-control custom-radio custom-control-inline">
    <%= form.label :thumbnail_type, class: 'radio inline' do %>
      <%= form.radio_button :thumbnail_type, 'Portrait', checked: true, class: 'form-check-input' %>
      <span class="form-check-label">Portrait</span>
    <% end %>
  </div>
  <div class="custom-control custom-radio custom-control-inline">
    <%= form.label :thumbnail_type, class: 'radio inline' do %>
      <%= form.radio_button :thumbnail_type, 'Landscape', class: 'form-check-input' %>
      <span class="form-check-label">Landscape</span>
    <% end %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content, :class => "tinymce"%>
    <script type="text/javascript">
        tinyMCE.init({
            selector: 'textarea',
            plugins: 'autosave advlist autolink lists link searchreplace media table paste imagetools wordcount image autoresize lists nonbreaking',
            toolbar: 'insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | numlist bulist outdent indent link image nonbreaking',
            min_height: 300,
            style_formats: [
                {
                    title: 'Image Left', selector: 'img', styles: {
                        'float': 'left',
                        'margin': '0 10px 0 10px'
                    }
                },
                {
                    title: 'Image Right', selector: 'img', styles: {
                        'float': 'right',
                        'margin': '0 10px 0 10px'
                    }
                }
            ],
            //List settings
            lists_indent_on_tab: true,
            nonbreaking_force_tab: true,
            //Image settings
            /* enable title field in the Image dialog*/
            image_title: true,
            image_caption: true,
            image_advtab: true,
            /* enable automatic uploads of images represented by blob or data URIs*/
            automatic_uploads: true,
            /*
              URL of our upload handler (for more details check: https://www.tiny.cloud/docs/configure/file-image-upload/#images_upload_url)
              images_upload_url: 'postAcceptor.php',
              here we add custom filepicker only to Image dialog
            */
            file_picker_types: 'image',
            /* and here's our custom image picker*/
            file_picker_callback: function (cb, value, meta) {
                var input = document.createElement('input');
                input.setAttribute('type', 'file');
                input.setAttribute('accept', 'image/*');

                /*
                  Note: In modern browsers input[type="file"] is functional without
                  even adding it to the DOM, but that might not be the case in some older
                  or quirky browsers like IE, so you might want to add it to the DOM
                  just in case, and visually hide it. And do not forget do remove it
                  once you do not need it anymore.
                */

                input.onchange = function () {
                    var file = this.files[0];

                    var reader = new FileReader();
                    reader.onload = function () {
                        /*
                          Note: Now we need to register the blob in TinyMCEs image blob
                          registry. In the next release this part hopefully won't be
                          necessary, as we are looking to handle it internally.
                        */
                        var id = 'blobid' + (new Date()).getTime();
                        var blobCache = tinymce.activeEditor.editorUpload.blobCache;
                        var base64 = reader.result.split(',')[1];
                        var blobInfo = blobCache.create(id, file, base64);
                        blobCache.add(blobInfo);

                        /* call the callback and populate the Title field with the file name */
                        cb(blobInfo.blobUri(), {title: file.name});
                    };
                    reader.readAsDataURL(file);
                };

                input.click();
            }
        });
    </script>
  </div>

  <div>
    <%= form.submit "#{yield(:page_title)}", data: { disable_with: 'Loading...' }, class: 'btn' %>
  </div>
<% end %>

app/views/events/_publish.html.erb
<%= link_to 'Publish', publish_event_path(event.id), method: :put, remote: true, data: {confirm: 'Are you sure?'} %>

app/views/events/_resources.html.erb
<% if event.images.attached? %>
  <div class="container">
    <h3>images</h3>
    <ul>
      <% event.images.each do |image| %>
        <li>
          <% if !image.id.nil? %>
            <%=
              link_to image.filename,
                      rails_blob_path(image, disposition: :attachment)
            %>
            |
            <%=
              link_to 'delete',
                      delete_image_event_path(images_id: image.id, event_id: event.id),
                      method: :delete,
                      data: {confirm: 'Are you sure?'}
            %>
          <% end %>
        </li>
      <% end %>
    </ul>
  </div>
<% end %>

<% if event.thumbnail.attached? %>
  <div class="container">
    <h3>thumbnail</h3>
    <ul>
      <li>
        <% if !event.thumbnail.id.nil? %>
          <%=
            link_to event.thumbnail.filename,
                    rails_blob_path(event.thumbnail, disposition: :attachment)
          %>
          |
          <%=
            link_to 'delete',
                    delete_image_event_path(images_id: event.thumbnail.id, event_id: event.id),
                    method: :delete,
                    data: {confirm: 'Are you sure?'}
          %>
        <% end %>
      </li>
    </ul>
  </div>
<% end %>

app/views/events/_unpublish.html.erb
<%= link_to 'Unpublish', unpublish_event_path(event.id), method: :put, remote: true, data: {confirm: 'Are you sure?'} %>

app/views/events/edit.html.erb
<% provide(:page_title, "Edit Event") %>

<div class="container">

  <h1>Editing Event</h1>

  <%= render 'form', event: @event %>
</div>

app/views/events/front.html.erb
<% provide(:page_title, "My Posts") %>

<p id="notice"><%= notice %></p>

<div class='container-fluid'>
  <div class="row ml-5 pl-1">
    <div class="col">
      <h1><strong>Posts</strong></h1>
    </div>
  </div>

  <div class="row ml-5 pl-3">
    <%= link_to 'New Event', new_event_path, class: 'btn' %>
  </div>

  <div class="row mx-5" id="admin-card">
    <!-- Card -->
    <% @events.each do |event| %>
      <div class="col-md-6 col-lg-4 mt-5">
        <div>
          <div class="card height-10 event-card shadow">
            <!--Card image-->
            <div class="bg-dark d-flex justify-content-center">
              <% if event.thumbnail.attached? %>
                <% if event.thumbnail_type.eql?("Portrait") %>
                  <%= image_tag event.thumbnail, class: 'portrait' %>
                <% else %>
                  <%= image_tag event.thumbnail, class: 'landscape' %>
                <% end %>
              <% end %>
            </div>

            <!--Card content-->
            <div class="card-body">
              <!--Title-->
              <h4 class="card-title"><%= event.title %></h4><!--Text-->
              <% if !event.start_date.nil? && !event.end_date.nil? %>
                <p class="card-text">
                  Date: <%= event.start_date.strftime("%d %b %Y") %> - <%= event.end_date.strftime("%d %b %Y") %>
                </p>
              <% end %>
              <!-- Provides extra visual weight and identifies the primary action in a set of buttons -->
              <div id="publish-btn-<%= event.id %>">
                <% if event.published? %>
                  <%= render 'unpublish', event: event %>
                <% else %>
                  <%= render 'publish', event: event %>
                <% end %>
              </div>
              <%= link_to 'Show', event %>
              <%= link_to 'Edit', edit_event_path(event) %>
              <%= link_to 'Destroy', event, method: :delete, data: {confirm: 'Are you sure?'} %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
    <!-- End of Card -->
  </div>

  <div class="row justify-content-center mt-3">
    <%= will_paginate @events, class: 'pagination' %>
  </div>

</div>

app/views/events/index.html.erb
<% provide(:page_title, @title) %>

<section id="events">
  <div class="container">
    <div class="row mt-3">
      <div class="col d-flex justify-content-center">
        <% if yield(:page_title) == "Upcoming" %>
          <h1>Upcoming</h1>
        <% else %>
          <h1>Past Events</h1>
        <% end %>
      </div>
    </div>
    <% if !@events.nil? %>
      <div class="row">
        <%= render @events %>
      </div>

      <div class="row justify-content-center mt-5">
        <%= will_paginate @events, class: 'pagination' %>
      </div>

    <% else %>
      <div class="row">
        <div class="col px-0">
          <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item">
              <a class="nav-link active" id="production-tab" data-toggle="tab" href="#production" role="tab" aria-controls="production" aria-selected="true">Performance
                & Production</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="profile-tab" data-toggle="tab" href="#profile" role="tab" aria-controls="profile" aria-selected="false">Musical
                Development</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" id="bonding-tab" data-toggle="tab" href="#bonding" role="tab" aria-controls="bonding" aria-selected="false">Bonding
                Activities</a>
            </li>
          </ul>
        </div>
      </div>
      <div class="row">
        <div class="tab-content" id="myTabContent" style="width: 100%;">
          <div class="tab-pane fade show active" id="production" role="tabpanel" aria-labelledby="production-tab">
            <div class="row height">
              <% if @production_events %>
                <div class="container-fluid">
                  <div class="row">
                    <%= render @production_events %>
                  </div>
                </div>
                <div class="container">
                  <div class="row justify-content-center pt-3 m-0" style="width: 100%;">
                    <%= will_paginate @production_events, class: 'pagination' %>
                  </div>
                </div>
              <% end %>

            </div>
          </div>
          <div class="tab-pane fade" id="profile" role="tabpanel" aria-labelledby="profile-tab">
            <% if @development_events %>
              <div class="conatiner-fluid">
                <div class="row">
                  <%= render @development_events %>
                </div>
              </div>
              <div class="container">
                <div class="row justify-content-center pt-3 m-0" style="width: 100%;">
                  <%= will_paginate @development_events, class: 'pagination' %>
                </div>
              </div>
            <% end %>
          </div>
          <div class="tab-pane fade" id="bonding" role="tabpanel" aria-labelledby="bonding-tab">
            <% if @bonding_events %>
              <div class="container-fluid">
                <div class="row">
                  <%= render @bonding_events %>
                </div>
              </div>
              <div class="container">
                <div class="row justify-content-center pt-3 m-0" style="width: 100%;">
                  <%= will_paginate @bonding_events, class: 'pagination' %>
                </div>
              </div>
            <% end %>
          </div>
        </div>
      </div>

    <% end %>

  </div>
</section>

app/views/events/new.html.erb
<% provide(:page_title, "New Event") %>

<div class="container">

  <h1>New Event</h1>

  <%= render 'form', event: @event %>
</div>

app/views/events/publish.js.erb
$("#publish-btn-<%= @event.id %>").html("<%= escape_javascript(render partial: 'events/unpublish', locals: {event: @event}) %>");
$("#navbar").html("<%= escape_javascript(render partial: 'layouts/navbar') %>")

app/views/events/show.html.erb
<% provide(:page_title, @event.title) %>

<div class="container-fluid mt-5 p-0">
  <div class="row">
    <div class="col">
      <h1 class="title"><%= @event.title %></h1>
    </div>
  </div>
  <% if @event.thumbnail.attached? %>
    <% if @event.thumbnail_type == 'Portrait' %>
      <div class="row pt-4 mx-4">
        <div class="col-md-6 px-0 m-0">
          <%= image_tag @event.thumbnail, class: 'portrait' %>
        </div>
        <div class="col-md-6 px-0 bg-light">
          <div class="event-content">
            <%= @event.content.html_safe %>
          </div>
        </div>
      </div>
    <% else %>
      <div class="row pt-4 mx-4">
        <div class="col-md-7 px-0 m-0">
          <%= image_tag @event.thumbnail, class: 'img-fluid' %>
        </div>
        <div class="col-md-5 px-0 bg-light" id="event-content">
          <div class="event-content">
            <%= @event.content.html_safe %>
          </div>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="col px-0 bg-light" id="event-content">
      <div class="event-content">
        <%= @event.content.html_safe %>
      </div>
    </div>
  <% end %>
</div>


<% if @event.images.attached? %>
  <div class="container-fluid mt-5">
    <div class="row justify-content-center">
      <h1 class="title"><%= @event.title %></h1>
    </div>
    <div class="row">
      <div id="wrapper">
        <div id="slider">
          <% @event.images.each do |image| %>
            <div class="slide" style="background-image: url(<%= url_for(image) %>); background-repeat: no-repeat; background-size: cover; background-position: center">
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript">
    $(function () {
        $('#slider').carouFredSel({
            width: '100%',
            align: false,
            items: 3,
            items: {
                width: $('#wrapper').width() * 0.15,
                height: 500,
                visible: 1,
                minimum: 1
            },
            scroll: {
                items: 1,
                timeoutDuration: 5000,
                onBefore: function (data) {

                    //	find current and next slide
                    var currentSlide = $('.slide.active', this),
                        nextSlide = data.items.visible,
                        _width = $('#wrapper').width();

                    //	resize currentslide to small version
                    currentSlide.stop().animate({
                        width: _width * 0.15
                    });
                    currentSlide.removeClass('active');

                    //	hide current block
                    data.items.old.add(data.items.visible).find('.slide-block').stop().fadeOut();

                    //	animate clicked slide to large size
                    nextSlide.addClass('active');
                    nextSlide.stop().animate({
                        width: _width * 0.7
                    });
                },
                onAfter: function (data) {
                    //	show active slide block
                    data.items.visible.last().find('.slide-block').stop().fadeIn();
                }
            },
            onCreate: function (data) {

                //	clone images for better sliding and insert them dynamacly in slider
                var newitems = $('.slide', this).clone(true),
                    _width = $('#wrapper').width();

                $(this).trigger('insertItem', [newitems, newitems.length, false]);

                //	show images
                $('.slide', this).fadeIn();
                $('.slide:first-child', this).addClass('active');
                $('.slide', this).width(_width * 0.15);

                //	enlarge first slide
                $('.slide:first-child', this).animate({
                    width: _width * 0.7
                });

                //	show first title block and hide the rest
                $(this).find('.slide-block').hide();
                $(this).find('.slide.active .slide-block').stop().fadeIn();
            }
        });

        //	Handle click events
        $('#slider').children().click(function () {
            $('#slider').trigger('slideTo', [this]);
        });

        //	Enable code below if you want to support browser resizing
        $(window).resize(function () {

            var slider = $('#slider'),
                _width = $('#wrapper').width();

            //	show images
            slider.find('.slide').width(_width * 0.15);

            //	enlarge first slide
            slider.find('.slide.active').width(_width * 0.7);

            //	update item width config
            slider.trigger('configuration', ['items.width', _width * 0.15]);
        });

    });
</script>

app/views/events/unpublish.js.erb
$("#publish-btn-<%= @event.id %>").html("<%= escape_javascript(render partial: 'events/publish', locals: {event: @event}) %>");
$("#navbar").html("<%= escape_javascript(render partial: 'layouts/navbar') %>")