config/routes.rb
Rails.application.routes.draw do
  resources :faqs
  root 'static_pages#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :sessions, only:[:create]
  resources :registrations, only:[:create]
  

  # events
  get '/events/front' => 'events#front', as: :manage_posts
  resources :events do
    member do
      delete :delete_image
    end

  	put 'publish' => 'events#publish',
  	on: :member, as: :publish
  
  	put 'unpublish' => 'events#unpublish', 
  	on: :member, as: :unpublish
  end

  #resources :messages
  resources :messages, :path => "contact_us"

  #static_pages
  get "/about" , to: 'static_pages#about'
  get "/join_us", to: 'messages#new'
  get "/home", to: 'static_pages#home'
  get "/maintenance", to: 'static_pages#maintenance'

  #sessions
  get "/login", to: 'sessions#new'
  post "/login", to: 'sessions#create'
  delete "/logout", to: 'sessions#logout'
  get "sessions/status"

  #registrations
  get "/signup", to: 'registrations#new'
  post "/signup", to: 'registrations#create'

  #search_page
  get '/search', to: 'search_page#search'

  #sitemap
  get '/sitemap', to: 'sitemap#index', defaults: {format: "xml"}
end

app/views/layouts/_footer.html.erb
<footer class="footer-distributed mt-0">

  <div class="footer-left">

    <h3><%= phrase('NUS') %> <span><%= phrase('Guitar Ensemble') %></span></h3>

    <p class="footer-links">
      <%= link_to 'Home', root_url %>
      ·
      <%= link_to 'About', about_path %>
      ·
      <%= link_to 'Upcoming', events_path(event_type: "Upcoming") %>
      ·
      <%= link_to 'Gallery', events_path %>
      ·
      <%= link_to 'Contact', join_us_path %>
    </p>

    <p class="footer-company-name"><%= phrase('A member of NUS Center For the Arts') %></p>

    <hr>

    <p class="text-light" style="font-size: 10px;">Icons made by <a href="https://www.flaticon.com/authors/freepik" title="Freepik">Freepik</a> from
      <a href="https://www.flaticon.com/"  title="Flaticon">www.flaticon.com</a> is licensed by
      <a href="http://creativecommons.org/licenses/by/3.0/"   title="Creative Commons BY 3.0" target="_blank">
        CC 3.0 BY</a></p>
  </div>

  <div class="footer-center">

    <div>
      <i class="fas fa-map-marker-alt"></i>
      <p><span><%= phrase('17 Kent Ridge Cresent') %></span> <%= phrase('Runme Shaw CFA Studios') %></p>
    </div>

    <div>
      <i class="fa fa-phone"></i>
      <p><%= phrase('+65 9879 1096') %></p>
    </div>

    <div>
      <i class="fa fa-envelope"></i>
      <p><a href="mailto:nusguitarensemble@gmail.com"><%= phrase('nusguitarensemble@gmail.com') %></a></p>
    </div>

  </div>

  <div class="footer-right">

    <p class="footer-company-about">
      <span><%= phrase('Follow us on:') %></span>
    </p>

    <div class="footer-icons">
      <a href="https://www.facebook.com/NUSGuitarEnsemble/"><i class="fab fa-facebook-f"></i></a>
      <a href="https://www.youtube.com/user/NusGuitarEnsemble"><i class="fab fa-youtube"></i></a>
      <a href="https://www.instagram.com/nusguitarensemble/"><i class="fab fa-instagram"></i></a>

    </div>

  </div>

</footer>

app/views/layouts/_header.html.erb
<% if yield(:page_title).eql?("NUS") %>

  <div class="container-fluid">
    <div class="row">
      <div class="col p-0">
        <div>
          <nav class="navbar navbar-expand-lg navbar-dark py-1" id="navbar">
            <%= render 'layouts/navbar' %>
          </nav>
        </div>
      </div>
    </div>

    <div class="row home-bg">
      <div class="container">
        <div class="row justify-content-center mt-3 welcome" id="welcome-word">
            <%= image_tag "welcome.png" %>
        </div>

        <div class="row">
          <div class="col">
            <div class="container mb-0">
              <div class="row">
                <div class="col">
                  <h1 class="home-text m-0"><%= phrase('NUS GUITAR ENSEMBLE') %></h1>
                </div>
              </div>
              <div class="row">
                <div class="col-2">

                </div>
                <div class="col-3">
                  <hr>
                </div>
                <div class="col-2 d-flex text-light align-items-center justify-content-center p-0">
                  <h2 class="font-italic m-0 text-center"><%= phrase('GENUS') %></h2>
                </div>
                <div class="col-3">
                  <hr>
                </div>
                <div class="col-2">

                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col d-flex justify-content-center">
            <p class="font-italic m-0"><%= phrase('A member of NUS Center For the Arts') %></p>
          </div>
        </div>

        <!-- begin of 4 icons -->
        <div class="row">
          <div class="container d-flex justify-content-center pt-5 mt-1">
            <div class="row">
              <div class="col-6 col-md-3">
                <div class="d-flex justify-content-center">
                  <%= link_to events_path(event_type: "Gallery") do %>
                    <i class="fas fa-photo-video fa-3x"></i>
                  <% end %>
                </div>
                <h5><%= phrase('Gallery') %></h5>
                <p><%= phrase('Check out our key events!') %></p>
              </div>

              <div class="col-6 col-md-3">
                <div class="d-flex justify-content-center">
                  <%= link_to events_path(event_type: "Upcoming") do %>
                    <i class="far fa-calendar-check fa-3x"></i>
                  <% end %>
                </div>
                <h5><%= phrase('Calendar') %></h5>
                <p><%= phrase('Find out more about upcoming events!') %></p>
              </div>

              <div class="col-6 col-md-3">
                <div class="d-flex justify-content-center">
                  <a href="https://www.youtube.com/user/NusGuitarEnsemble" target="_blank"><i class="fas fa-guitar fa-3x"></i></a>
                </div>
                <h5><%= phrase('Past Production') %></h5>
                <p><%= phrase('Watch videos from our previous concerts!') %></p>
              </div>

              <div class="col-6 col-md-3">
                <div class="d-flex justify-content-center">
                  <%= link_to join_us_path do %>
                    <i class="far fa-address-book fa-3x"></i>
                  <% end %>
                </div>
                <h5><%= phrase('Contact Us') %></h5>
                <p><%= phrase('For any inquiries') %></p>
              </div>
            </div>
          </div>
        </div>
        <!-- end of 4 icons -->

      </div>
    </div>
  </div>

<% else %>

  <div class="container-fluid">
    <div class="row">
      <div class="col p-0">
        <nav class="navbar navbar-expand-lg navbar-dark" id="navbar">
          <%= render 'layouts/navbar' %>
        </nav>
      </div>
    </div>
  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    if ($(window).width() < 768) {
        $('#welcome-word').html('<h2 class="text-light p-0 m-0 text-center" style="font-size: 1rem;">WELCOME TO</h2>');
    } else {
        $('#welcome-word').html('<%= image_tag "welcome.png" %>');
    }
</script>

app/views/layouts/_navbar.html.erb
<%= link_to root_url do %>
  <div class="container logo">
    <div class="row">
      <div class="col-3 text-light">
        <%= image_tag "genus_logo_no_bg.png", class: "pr-4"%>
      </div>
      <div class="col-9 pl-2">
        GENUS
      </div>
    </div>
    <!--
    <div class="row" style="font-size: 0.5em">
      NUS GUITAR ENSEMBLE
    </div>
    -->
  </div>
<% end %>

<button class="navbar-toggler text-light" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
  <span class="navbar-toggler-icon"></span>
</button>

<div class="collapse navbar-collapse dropDownMenu" id="navbarSupportedContent">
  <ul class="navbar-nav ml-auto">
    <li class="nav-item active">
      <%= link_to "Home", root_url, class: 'nav-link text-light' %>
    </li>

    <li>
      <%= link_to about_path, class: 'nav-link text-light' do %>
        About <i class="fas fa-caret-down" id="down-arrow"></i>
      <% end %>
      <ul class="p-1">
        <li class="py-1 ml-2">
          <%= link_to "About GENUS", about_path(anchor: 'genus'), class: 'nav-link text-light ml-0 pl-0' %>
        </li>
        <hr class="p-0 m-0">

        <li class="py-1 ml-2">
          <%= link_to "Our Mission Vision Values", about_path(anchor: 'mvv'), class: 'nav-link text-light ml-0 pl-0' %>
        </li>
        <hr class="p-0 m-0">

        <li class="py-1 ml-2">
          <%= link_to "Our Founder", about_path(anchor: 'founder'), class: 'nav-link text-light ml-0 pl-0' %>
        </li>

        <hr class="p-0 m-0">

        <li class="py-1 ml-2">
          <%= link_to 'Our Music Director & Resident Conductor', about_path(anchor: 'tutors'), class: 'nav-link text-light ml-0 pl-0' %>
        </li>

        <hr class="p-0 m-0">


<!--        <li class="py-1 ml-2">     -->
          <%#= link_to "Our Tutors", about_path(anchor: 'tutors'), class: 'nav-link text-light ml-0 pl-0' %>
<!--        </li>       -->

        <hr class="p-0 m-0">

        <li class="py-1 ml-2">
          <%= link_to "The Niibori Method", about_path(anchor: 'niibori-method'), class: 'nav-link text-light ml-0 pl-0' %>
        </li>

        <hr class="p-0 m-0">

        <li class="py-1 ml-2">
          <%= link_to "Schedule", about_path(anchor: 'schedule'), class: 'nav-link text-light ml-0 pl-0' %>
        </li>

      </ul>
    </li>

    <li>
      <%= link_to events_path(event_type: "Upcoming"), class: 'nav-link text-light' do %>
        Upcoming Events <i class="fas fa-caret-down" id="down-arrow-1"></i>
      <% end %>
      <% if upcoming_events = Event.where("event_type = ? AND published = ?", 'Upcoming', true) %>
        <% if upcoming_events.any? %>
          <ul class="p-1">
            <% upcoming_events.each do |event| %>
              <% if (event == upcoming_events.last || upcoming_events.count == 1) %>
                <li class="py-1 ml-2">
                  <%= link_to "#{event.title}", event_path(event), class: 'nav-link text-light ml-0 pl-0' %>
                </li>
              <% else %>
                <li class="py-1 ml-2">
                  <%= link_to "#{event.title}", event_path(event), class: 'nav-link text-light ml-0 pl-0' %>
                </li>
                <hr class="p-0 m-0">
              <% end %>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </li>

    <li>
      <%= link_to events_path, class: 'nav-link text-light' do %>
        Gallery <i class="fas fa-caret-down" id="down-arrow-2"></i>
      <% end %>
      <% if gallery_events = Event.where.not("event_type = ?", 'Upcoming').where("published = ?", true) %>
        <% if gallery_events.any? %>
          <ul class="p-1">
            <% gallery_events.each do |event| %>
              <% if (event == gallery_events.last || gallery_events.count == 1) %>
                <li class="py-1 ml-2">
                  <%= link_to "#{event.title}", event_path(event), class: 'nav-link text-light ml-0 pl-0' %>
                </li>
              <% else %>
                <li class="py-1 ml-2">
                  <%= link_to "#{event.title}", event_path(event), class: 'nav-link text-light ml-0 pl-0' %>
                </li>
                <hr class="p-0 m-0">
              <% end %>
            <% end %>
          </ul>
        <% end %>
      <% end %>
    </li>

    <li>
      <%= link_to "Contact Us", new_message_path, class: 'nav-link text-light' %>
    </li>

    <li>
      <%= link_to "FAQs", faqs_path, class: 'nav-link text-light' %>
    </li>

    <% if @current_user %>
      <li>
        <%= link_to root_path, class: 'nav-link text-light' do %>
          Admin Actions <i class="fas fa-caret-down" id="down-arrow-3"></i>
        <% end %>
        <ul class="p-1">
          <li class="py-1 ml-2">
            <%= link_to "Manage Post", manage_posts_path, class: 'nav-link text-light' %>
          </li>
          <hr class="p-0 m-0">

          <li class="py-1 ml-2">
            <%= link_to "All Messages", messages_path, class: 'nav-link text-light' %>
          </li>
          <hr class="p-0 m-0">

          <li class="py-1 ml-2">
            <%= link_to "Create Admin", signup_path, method: :get, class: 'nav-link text-light' %>
          </li>

          <hr class="p-0 m-0">

          <li class="py-1 ml-2">
            <%= link_to "Log out", logout_path, method: :delete, class: 'nav-link text-light' %>
          </li>
        </ul>
      </li>
    <% end %>

  </ul>

  <!--Search bar-->
  <% if false %>
    <%= form_tag(search_path, :method => "get", class: 'navbar-form navbar-left') do %>
      <div class="input-group">
        <%= search_field_tag :search, params[:search], placeholder: "Search Events", class: "form-control" %>
        <div class="input-group-btn">
          <%= button_tag "Go!", :class => 'btn btn-info glyphicon glyphicon-search', :name => nil %>
        </div>
      </div>
    <% end %>
  <% end %>
  <!--Search bar end-->

</div>

<script type="text/javascript">
    if ($(window).width() < 992) {
        $('#down-arrow').addClass('no-display');
        $('#down-arrow-1').addClass('no-display');
        $('#down-arrow-2').addClass('no-display');
        $('#down-arrow-3').addClass('no-display');
    } else {
        $('.dropDownMenu ul li').hover(function () {
            $(this).children('ul').stop(true, false, true).slideToggle(300);
        });
    }
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Cantarell:400i&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Overlock&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Ubuntu&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Blinker|Crimson+Text|Farro|Grenze|Lacquer|Montserrat|Saira+Stencil+One&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Rubik&display=swap" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Indie+Flower&display=swap" rel="stylesheet">

  <head>
    <title><%= yield(:page_title) %> | Singapore | NUS Guitar Ensemble</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/b33f59b361.js"></script>

    <meta name="organisation" content="NUS | NUS Guitar Ensemble" />
    <meta name="description" content="Established in 1981 by Cultural Medallion recipient Mr Alex Abisheganaden, NUS Guitar Ensemble (GENUS) is Singapore’s leading guitar ensemble. Initially comprising only classical prime guitars, GENUS was later modelled after the Niibori Orchestra in Japan, becoming the pioneering Niibori guitar ensemble in Singapore." />
    <meta property="og:title" content="NUS | Singapore | NUS Guitar Ensemble" />
    <meta property="og:description" content="Established in 1981 by Cultural Medallion recipient Mr Alex Abisheganaden, NUS Guitar Ensemble (GENUS) is Singapore’s leading guitar ensemble. Initially comprising only classical prime guitars, GENUS was later modelled after the Niibori Orchestra in Japan, becoming the pioneering Niibori guitar ensemble in Singapore." />
    <meta property="og:url" content="https://www.nusguitarensemble.com" />
    <meta name="keywords" content="Niibori Guitars, Guitar Ensemble, Guitar, Music, NUS, Singapore, Classical Music, Japanese Music" />

    <!-- making responsive sites -->
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta name="google-site-verification" content="WS1S8USmKu9G-B75H6UsPPR7ZgAqpQcexsOUxw9kj8A" />
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('guitar2.ico') %>
  </head>

  <body>
    <%= render 'phrasing/initializer' %>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <% if message.kind_of?(Array) %>
          <% message.each do |msg| %>
              <%= content_tag(:div, msg, class: "alert alert-#{message_type}") %>
          <% end %>
        <% else %>
          <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
        <% end %>
      <% end %>
    </div>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>